# -*- coding: utf-8 -*-
"""Tugas 2 Pemodelan MTK_662023001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vkVOA_TBO3Q8w3kvP2qcdNdwYMLJEViN
"""

print("Nama = Pramudya Riandanu")
print("NIM = 662023001")

# import package
import numpy as np
import matplotlib.pyplot as plt

# Fungsi untuk menyelesaikan persamaan diferensial secara analitik
def perubahan_ekonomi(t, Po, Pa, Pi, k):
    """
    Menyelesaikan P = Pa + e^(k * t) * To -Pi

    Parameter:
        P : Jumlah kekayaan
        t : waktu
        Po : Kekayaan awal saat t = tahun pertama dalam list
        Pa : Pengeluaran
        Pi : Pemasukan
        k = konstanta laju ekonomi


    Mengembalikan:
        P : array-like, kekayaan
    """
    return Pa + np.exp(k * t) * Po - Pi

# Parameter contoh
Po = 900000000  #kekayaan awal
Pa = 14000000  #pengeluaran
Pi = 32000000  #pemasukan
k = 0.1   # Konstanta laju perubahan ekonomi
t = np.linspace(0, 25, 5)  # Titik waktu dari 0(tahun ke 0) hingga 24(tahun ke 24)

# Menyelesaikan persamaan
P = perubahan_ekonomi(t, Po, Pa, Pi, k)

# Plot hasilnya
plt.figure(figsize=(8, 6))
plt.plot(t, P, label=f"P = {Pa} + exp({k} * t) * Po - {Pi}", color="magenta")
plt.title("Perubahan laju ekonomi satu keluarga")
plt.xlabel("Waktu (t)")
plt.ylabel("kekayaan (T)")
plt.legend()
plt.grid()
plt.show()