# -*- coding: utf-8 -*-
"""Tugas_3_PM_662023001_Pramudya Riandanu(Kodingan).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bsO6e40ooA1WFW9bxXtW4My5QHmhemu3
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

#Parameter model
beta = 0.2 # Laju infeksi
gamma = 1/10 # Laju pemulihan (1/gamma = 10 hari)
alpha = 0.76 # Laju kelahiran(dalam 100 hari ada 76 bayi yang lahir)
sigma = 0.3 # Laju kematian(dalam 10 hari ada 3 orang meninggal)

N = 1000 # Total populasi

#Kondisi awal
S0 = N -1 # Semua individu rentan kecuali 1 yang terinfeksi
I0 = 1 # Individu terinfeksi pada awalnya
R0 = 0 # Tidak ada yang sembuh pada awalnya

# Waktu simulasi (dalam hari)
t = np.linspace(0, 160, 160) # Simulasi selama 160 hari

# Model SIR
def sir_model(y, t, N, beta, gamma, alpha, sigma):
    S, I, R = y
    dSdt = alpha * N -beta * S * I / N -sigma * S
    dIdt = beta * S * I /N - gamma * I - sigma * I
    dRdt = gamma * I - sigma * R
    return [dSdt, dIdt, dRdt]

#Menyelesaikan sistem persamaan diferensial
y0 = [S0, I0, R0]
solution = odeint(sir_model, y0, t, args=(N, beta, gamma, alpha, sigma))
S, I, R = solution.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, I, label='Infected', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Hari')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SIR')
plt.legend()
plt.grid()
plt.show()

