# -*- coding: utf-8 -*-
"""Praktikum 3 PM Pramudya Riandanu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTiOTxazxABd5-9QNWBdY5cqIrc0oa7E
"""

import numpy as np

A = np.array([[4, 1],[-2, 3]])

nilaieigen, vectoreigen = np.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvectoreigen")
print(vectoreigen)