# -*- coding: utf-8 -*-
"""Lokta-Volterra Praktikum 5 Pramudya Riandanu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdfc9aK44FBh35xZJrg-b47k76XqMn6S
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

#parameter model
alpha = 0.5 #Laju pertumbuhan mangsa(rusa)
beta = 0.02 #Tingkat perburuan oleh predator (serigala)
delta = 0.01 #Efisiensi konversi mangsa menjadi predator
gamma = 0.3 # Tingkat kematian alami predator

#Persamaan diferessial Lotka-Volterra
def lotka_volterra(y, t, alpha, beta, delta, gamma):
  x, y = y
  dxdt = alpha * x - beta * x * y #Perubahan populasi rusa
  dydt = delta * x * y - gamma * y # Perubahan populasi serigala
  return [dxdt, dydt]

#kondisi awal; jumlah awal rusa dan serigala
y0 = [40, 9]

#Rentang waktu simulasi (0 sampai 200 unit waktu)
t = np.linspace(0, 200, 1000)

#Menyelesaikan persamaan diferensial
solution = odeint(lotka_volterra, y0, t, args=(alpha, beta, delta, gamma))
rusa, serigala = solution.T #Memisahkan hasil ke dua variabel

#Membuat grafik hasil simulasi
plt.figure(figsize=(10, 5))
plt.plot(t, rusa, label="Rusa(Prey)", color="blue", linewidth=2)
plt.plot(t, serigala, label="Serigala (Predator)", color="red", linewidth=2)
plt.xlabel("Waktu")
plt.ylabel("Populasi")
plt.title("Simulasi Model Lotka-Volterra : Pertarungan antara Rusa dan Serigala")
plt.legend()
plt.grid()
plt.show()