# -*- coding: utf-8 -*-
"""Tugas_3_Pramudya Riandanu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5J14wTF9bDFO_zaP9bhFe9qDOlJ1uxi
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

#Parameter model
beta = 0.2 # Laju infeksi
gamma = 1/10 # Laju pemulihan (1/gamma = 10 hari)

N = 1000 # Total populasi

#Kondisi awal
S0 = N -1 # Semua individu rentan kecuali 1 yang terinfeksi
I0 = 1 # Individu terinfeksi pasa awalnya
R0 = 0 # Tidak ada yang sembuh pasa awalnya

# Waktu simulasi (dalam hari)
t = np.linspace(0, 160, 160) # Simulasi selama 160 hari

# Model SIR
def sir_model(y, t, N, beta, gamma):
    S, I, R = y
    dSdt = -beta * S * I / N
    dIdt = beta * S * I /N - gamma * I
    dRdt = gamma * I
    return [dSdt, dIdt, dRdt]

#Menyelesaikan sistem persamaan diferensial
y0 = [S0, I0, R0]
solution = odeint(sir_model, y0, t, args=(N, beta, gamma))
S, I, R = solution.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, I, label='Infected', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Hari')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SIR')
plt.legend()
plt.grid()
plt.show()

